#############################################################################
# Makefile for building: gra
# Generated by qmake (3.1) (Qt 5.9.5)
# Project:  out/pro/gra.pro
# Template: app
# Command: /usr/lib/qt5/bin/qmake -o Makefile.app out/pro/gra.pro
#############################################################################

MAKEFILE      = Makefile.app

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_DEPRECATED_WARNINGS -DQT_NO_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_SERIALPORT_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -O2 -Wall -W -D_REENTRANT -fPIC $(DEFINES)
CXXFLAGS      = -pipe -g -O2 -Wall -W -D_REENTRANT -fPIC $(DEFINES)
INCPATH       = -Iout/pro -I. -Iinc -Iui/inc -I.inc -I./res/inc -I./ui/inc -isystem /usr/include/x86_64-linux-gnu/qt5 -isystem /usr/include/x86_64-linux-gnu/qt5/QtWidgets -isystem /usr/include/x86_64-linux-gnu/qt5/QtGui -isystem /usr/include/x86_64-linux-gnu/qt5/QtSerialPort -isystem /usr/include/x86_64-linux-gnu/qt5/QtCore -Iout/moc -isystem /usr/include/libdrm -Iout/uic -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++
QMAKE         = /usr/lib/qt5/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
QINSTALL      = /usr/lib/qt5/bin/qmake -install qinstall
QINSTALL_PROGRAM = /usr/lib/qt5/bin/qmake -install qinstall -exe
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = gra1.0.0
DISTDIR = /home/marcel/Documents/semestrVI/WDS/Qt/out/obj/gra1.0.0
LINK          = g++
LFLAGS        = -Wl,-O1
LIBS          = $(SUBLIBS) -lQt5Widgets -lQt5Gui -lQt5SerialPort -lQt5Core -lGL -lpthread 
AR            = ar cqs
RANLIB        = 
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = out/obj/

####### Files

SOURCES       = src/crc8.cpp \
		src/dialogs.cpp \
		src/gameWidget.cpp \
		src/gameWindow.cpp \
		src/main.cpp \
		src/mainWidget.cpp \
		src/odczyt.cpp \
		src/okno.cpp \
		src/oknogry.cpp \
		src/statisticWidget.cpp \
		src/test.cpp \
		src/widgetgry.cpp out/rcc/qrc_zasoby.cpp \
		out/moc/moc_dialogs.cpp \
		out/moc/moc_gameWidget.cpp \
		out/moc/moc_gameWindow.cpp \
		out/moc/moc_mainWidget.cpp \
		out/moc/moc_statisticWidget.cpp
OBJECTS       = out/obj/crc8.o \
		out/obj/dialogs.o \
		out/obj/gameWidget.o \
		out/obj/gameWindow.o \
		out/obj/main.o \
		out/obj/mainWidget.o \
		out/obj/odczyt.o \
		out/obj/okno.o \
		out/obj/oknogry.o \
		out/obj/statisticWidget.o \
		out/obj/test.o \
		out/obj/widgetgry.o \
		out/obj/qrc_zasoby.o \
		out/obj/moc_dialogs.o \
		out/obj/moc_gameWidget.o \
		out/obj/moc_gameWindow.o \
		out/obj/moc_mainWidget.o \
		out/obj/moc_statisticWidget.o
DIST          = /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/sanitize.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_egl_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fb_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_glx_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_input_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_serialport.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_service_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_theme_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf \
		out/pro/.qmake.stash \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/toolchain.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/moc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/opengl.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/uic.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/thread.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qmake_use.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/file_copies.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf \
		out/pro/out/pro/gra.pro inc/crc8.hpp \
		inc/dialogs.hpp \
		inc/gameWidget.hpp \
		inc/gameWindow.hpp \
		inc/mainWidget.hpp \
		inc/odczyt.hpp \
		inc/okno.hpp \
		inc/oknogry.hpp \
		inc/statisticWidget.hpp \
		inc/test.hpp \
		inc/widgetgry.hpp src/crc8.cpp \
		src/dialogs.cpp \
		src/gameWidget.cpp \
		src/gameWindow.cpp \
		src/main.cpp \
		src/mainWidget.cpp \
		src/odczyt.cpp \
		src/okno.cpp \
		src/oknogry.cpp \
		src/statisticWidget.cpp \
		src/test.cpp \
		src/widgetgry.cpp
QMAKE_TARGET  = gra
DESTDIR       = 
TARGET        = gra


first: all
####### Build rules

$(TARGET): out/uic/ui_aplicationmainwindow.h out/uic/ui_conDialog.h out/uic/ui_disDialog.h out/uic/ui_gameWidget.h out/uic/ui_gameWidgetv2.h out/uic/ui_gameWindow.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile.app: out/pro/gra.pro /usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/sanitize.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_egl_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fb_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_glx_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_input_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_serialport.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_service_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_theme_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/toolchain.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/moc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/opengl.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/uic.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/thread.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qmake_use.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/file_copies.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf \
		out/pro/gra.pro \
		res/zasoby.qrc \
		/usr/lib/x86_64-linux-gnu/libQt5Widgets.prl \
		/usr/lib/x86_64-linux-gnu/libQt5Gui.prl \
		/usr/lib/x86_64-linux-gnu/libQt5SerialPort.prl \
		/usr/lib/x86_64-linux-gnu/libQt5Core.prl
	$(QMAKE) -o Makefile.app out/pro/gra.pro
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/sanitize.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_egl_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fb_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_glx_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_input_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_kms_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_serialport.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_service_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_theme_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf:
.qmake.stash:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/toolchain.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/moc.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/opengl.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/uic.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/thread.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qmake_use.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/file_copies.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf:
out/pro/gra.pro:
res/zasoby.qrc:
/usr/lib/x86_64-linux-gnu/libQt5Widgets.prl:
/usr/lib/x86_64-linux-gnu/libQt5Gui.prl:
/usr/lib/x86_64-linux-gnu/libQt5SerialPort.prl:
/usr/lib/x86_64-linux-gnu/libQt5Core.prl:
qmake: FORCE
	@$(QMAKE) -o Makefile.app out/pro/gra.pro

qmake_all: FORCE


all: Makefile.app $(TARGET)

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents res/zasoby.qrc $(DISTDIR)/
	$(COPY_FILE) --parents /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/data/dummy.cpp $(DISTDIR)/
	$(COPY_FILE) --parents inc/crc8.hpp inc/dialogs.hpp inc/gameWidget.hpp inc/gameWindow.hpp inc/mainWidget.hpp inc/odczyt.hpp inc/okno.hpp inc/oknogry.hpp inc/statisticWidget.hpp inc/test.hpp inc/widgetgry.hpp $(DISTDIR)/
	$(COPY_FILE) --parents src/crc8.cpp src/dialogs.cpp src/gameWidget.cpp src/gameWindow.cpp src/main.cpp src/mainWidget.cpp src/odczyt.cpp src/okno.cpp src/oknogry.cpp src/statisticWidget.cpp src/test.cpp src/widgetgry.cpp $(DISTDIR)/
	$(COPY_FILE) --parents ui/aplicationmainwindow.ui ui/conDialog.ui ui/disDialog.ui ui/gameWidget.ui ui/gameWidgetv2.ui ui/gameWindow.ui $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile.app


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all: out/rcc/qrc_zasoby.cpp
compiler_rcc_clean:
	-$(DEL_FILE) out/rcc/qrc_zasoby.cpp
out/rcc/qrc_zasoby.cpp: res/zasoby.qrc \
		/usr/lib/qt5/bin/rcc \
		res/img/plytka.png \
		res/img/tlo.png
	/usr/lib/qt5/bin/rcc -name zasoby res/zasoby.qrc -o out/rcc/qrc_zasoby.cpp

compiler_moc_predefs_make_all: out/moc/moc_predefs.h
compiler_moc_predefs_clean:
	-$(DEL_FILE) out/moc/moc_predefs.h
out/moc/moc_predefs.h: /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/data/dummy.cpp
	g++ -pipe -g -O2 -Wall -W -dM -E -o out/moc/moc_predefs.h /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/data/dummy.cpp

compiler_moc_header_make_all: out/moc/moc_dialogs.cpp out/moc/moc_gameWidget.cpp out/moc/moc_gameWindow.cpp out/moc/moc_mainWidget.cpp out/moc/moc_statisticWidget.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) out/moc/moc_dialogs.cpp out/moc/moc_gameWidget.cpp out/moc/moc_gameWindow.cpp out/moc/moc_mainWidget.cpp out/moc/moc_statisticWidget.cpp
out/moc/moc_dialogs.cpp: out/uic/ui_disDialog.h \
		out/uic/ui_conDialog.h \
		inc/dialogs.hpp \
		out/moc/moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include ./out/moc/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/marcel/Documents/semestrVI/WDS/Qt/out/pro -I/home/marcel/Documents/semestrVI/WDS/Qt/out/pro/inc -I/home/marcel/Documents/semestrVI/WDS/Qt/out/pro/ui/inc -I/home/marcel/Documents/semestrVI/WDS/Qt/out/pro/.inc -I/home/marcel/Documents/semestrVI/WDS/Qt/out/pro/res/inc -I/home/marcel/Documents/semestrVI/WDS/Qt/out/pro/ui/inc -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtSerialPort -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I. -I/usr/include/c++/7 -I/usr/include/x86_64-linux-gnu/c++/7 -I/usr/include/c++/7/backward -I/usr/lib/gcc/x86_64-linux-gnu/7/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/7/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include inc/dialogs.hpp -o out/moc/moc_dialogs.cpp

out/moc/moc_gameWidget.cpp: inc/mainWidget.hpp \
		inc/gameWindow.hpp \
		inc/dialogs.hpp \
		out/uic/ui_disDialog.h \
		out/uic/ui_conDialog.h \
		out/uic/ui_gameWindow.h \
		inc/gameWidget.hpp \
		inc/statisticWidget.hpp \
		out/uic/ui_gameWidget.h \
		inc/gameWidget.hpp \
		out/moc/moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include ./out/moc/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/marcel/Documents/semestrVI/WDS/Qt/out/pro -I/home/marcel/Documents/semestrVI/WDS/Qt/out/pro/inc -I/home/marcel/Documents/semestrVI/WDS/Qt/out/pro/ui/inc -I/home/marcel/Documents/semestrVI/WDS/Qt/out/pro/.inc -I/home/marcel/Documents/semestrVI/WDS/Qt/out/pro/res/inc -I/home/marcel/Documents/semestrVI/WDS/Qt/out/pro/ui/inc -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtSerialPort -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I. -I/usr/include/c++/7 -I/usr/include/x86_64-linux-gnu/c++/7 -I/usr/include/c++/7/backward -I/usr/lib/gcc/x86_64-linux-gnu/7/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/7/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include inc/gameWidget.hpp -o out/moc/moc_gameWidget.cpp

out/moc/moc_gameWindow.cpp: inc/mainWidget.hpp \
		inc/gameWindow.hpp \
		inc/dialogs.hpp \
		out/uic/ui_disDialog.h \
		out/uic/ui_conDialog.h \
		out/uic/ui_gameWindow.h \
		inc/gameWidget.hpp \
		inc/statisticWidget.hpp \
		out/uic/ui_gameWidget.h \
		inc/gameWindow.hpp \
		out/moc/moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include ./out/moc/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/marcel/Documents/semestrVI/WDS/Qt/out/pro -I/home/marcel/Documents/semestrVI/WDS/Qt/out/pro/inc -I/home/marcel/Documents/semestrVI/WDS/Qt/out/pro/ui/inc -I/home/marcel/Documents/semestrVI/WDS/Qt/out/pro/.inc -I/home/marcel/Documents/semestrVI/WDS/Qt/out/pro/res/inc -I/home/marcel/Documents/semestrVI/WDS/Qt/out/pro/ui/inc -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtSerialPort -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I. -I/usr/include/c++/7 -I/usr/include/x86_64-linux-gnu/c++/7 -I/usr/include/c++/7/backward -I/usr/lib/gcc/x86_64-linux-gnu/7/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/7/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include inc/gameWindow.hpp -o out/moc/moc_gameWindow.cpp

out/moc/moc_mainWidget.cpp: inc/gameWindow.hpp \
		inc/mainWidget.hpp \
		inc/gameWidget.hpp \
		inc/statisticWidget.hpp \
		out/uic/ui_gameWidget.h \
		inc/dialogs.hpp \
		out/uic/ui_disDialog.h \
		out/uic/ui_conDialog.h \
		out/uic/ui_gameWindow.h \
		inc/mainWidget.hpp \
		out/moc/moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include ./out/moc/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/marcel/Documents/semestrVI/WDS/Qt/out/pro -I/home/marcel/Documents/semestrVI/WDS/Qt/out/pro/inc -I/home/marcel/Documents/semestrVI/WDS/Qt/out/pro/ui/inc -I/home/marcel/Documents/semestrVI/WDS/Qt/out/pro/.inc -I/home/marcel/Documents/semestrVI/WDS/Qt/out/pro/res/inc -I/home/marcel/Documents/semestrVI/WDS/Qt/out/pro/ui/inc -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtSerialPort -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I. -I/usr/include/c++/7 -I/usr/include/x86_64-linux-gnu/c++/7 -I/usr/include/c++/7/backward -I/usr/lib/gcc/x86_64-linux-gnu/7/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/7/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include inc/mainWidget.hpp -o out/moc/moc_mainWidget.cpp

out/moc/moc_statisticWidget.cpp: inc/mainWidget.hpp \
		inc/gameWindow.hpp \
		inc/dialogs.hpp \
		out/uic/ui_disDialog.h \
		out/uic/ui_conDialog.h \
		out/uic/ui_gameWindow.h \
		inc/gameWidget.hpp \
		inc/statisticWidget.hpp \
		out/uic/ui_gameWidget.h \
		inc/statisticWidget.hpp \
		out/moc/moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include ./out/moc/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/marcel/Documents/semestrVI/WDS/Qt/out/pro -I/home/marcel/Documents/semestrVI/WDS/Qt/out/pro/inc -I/home/marcel/Documents/semestrVI/WDS/Qt/out/pro/ui/inc -I/home/marcel/Documents/semestrVI/WDS/Qt/out/pro/.inc -I/home/marcel/Documents/semestrVI/WDS/Qt/out/pro/res/inc -I/home/marcel/Documents/semestrVI/WDS/Qt/out/pro/ui/inc -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtSerialPort -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I. -I/usr/include/c++/7 -I/usr/include/x86_64-linux-gnu/c++/7 -I/usr/include/c++/7/backward -I/usr/lib/gcc/x86_64-linux-gnu/7/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/7/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include inc/statisticWidget.hpp -o out/moc/moc_statisticWidget.cpp

compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: out/uic/ui_aplicationmainwindow.h out/uic/ui_conDialog.h out/uic/ui_disDialog.h out/uic/ui_gameWidget.h out/uic/ui_gameWidgetv2.h out/uic/ui_gameWindow.h
compiler_uic_clean:
	-$(DEL_FILE) out/uic/ui_aplicationmainwindow.h out/uic/ui_conDialog.h out/uic/ui_disDialog.h out/uic/ui_gameWidget.h out/uic/ui_gameWidgetv2.h out/uic/ui_gameWindow.h
out/uic/ui_aplicationmainwindow.h: ui/aplicationmainwindow.ui \
		/usr/lib/qt5/bin/uic
	/usr/lib/qt5/bin/uic ui/aplicationmainwindow.ui -o out/uic/ui_aplicationmainwindow.h

out/uic/ui_conDialog.h: ui/conDialog.ui \
		/usr/lib/qt5/bin/uic
	/usr/lib/qt5/bin/uic ui/conDialog.ui -o out/uic/ui_conDialog.h

out/uic/ui_disDialog.h: ui/disDialog.ui \
		/usr/lib/qt5/bin/uic
	/usr/lib/qt5/bin/uic ui/disDialog.ui -o out/uic/ui_disDialog.h

out/uic/ui_gameWidget.h: ui/gameWidget.ui \
		/usr/lib/qt5/bin/uic
	/usr/lib/qt5/bin/uic ui/gameWidget.ui -o out/uic/ui_gameWidget.h

out/uic/ui_gameWidgetv2.h: ui/gameWidgetv2.ui \
		/usr/lib/qt5/bin/uic
	/usr/lib/qt5/bin/uic ui/gameWidgetv2.ui -o out/uic/ui_gameWidgetv2.h

out/uic/ui_gameWindow.h: ui/gameWindow.ui \
		/usr/lib/qt5/bin/uic
	/usr/lib/qt5/bin/uic ui/gameWindow.ui -o out/uic/ui_gameWindow.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_rcc_clean compiler_moc_predefs_clean compiler_moc_header_clean compiler_uic_clean 

####### Compile

out/obj/crc8.o: src/crc8.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o out/obj/crc8.o src/crc8.cpp

out/obj/dialogs.o: src/dialogs.cpp inc/dialogs.hpp \
		out/uic/ui_disDialog.h \
		out/uic/ui_conDialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o out/obj/dialogs.o src/dialogs.cpp

out/obj/gameWidget.o: src/gameWidget.cpp inc/gameWidget.hpp \
		inc/mainWidget.hpp \
		inc/gameWindow.hpp \
		inc/dialogs.hpp \
		out/uic/ui_disDialog.h \
		out/uic/ui_conDialog.h \
		out/uic/ui_gameWindow.h \
		inc/statisticWidget.hpp \
		out/uic/ui_gameWidget.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o out/obj/gameWidget.o src/gameWidget.cpp

out/obj/gameWindow.o: src/gameWindow.cpp inc/gameWindow.hpp \
		inc/mainWidget.hpp \
		inc/gameWidget.hpp \
		inc/statisticWidget.hpp \
		out/uic/ui_gameWidget.h \
		inc/dialogs.hpp \
		out/uic/ui_disDialog.h \
		out/uic/ui_conDialog.h \
		out/uic/ui_gameWindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o out/obj/gameWindow.o src/gameWindow.cpp

out/obj/main.o: src/main.cpp inc/gameWindow.hpp \
		inc/mainWidget.hpp \
		inc/gameWidget.hpp \
		inc/statisticWidget.hpp \
		out/uic/ui_gameWidget.h \
		inc/dialogs.hpp \
		out/uic/ui_disDialog.h \
		out/uic/ui_conDialog.h \
		out/uic/ui_gameWindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o out/obj/main.o src/main.cpp

out/obj/mainWidget.o: src/mainWidget.cpp inc/mainWidget.hpp \
		inc/gameWindow.hpp \
		inc/dialogs.hpp \
		out/uic/ui_disDialog.h \
		out/uic/ui_conDialog.h \
		out/uic/ui_gameWindow.h \
		inc/gameWidget.hpp \
		inc/statisticWidget.hpp \
		out/uic/ui_gameWidget.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o out/obj/mainWidget.o src/mainWidget.cpp

out/obj/odczyt.o: src/odczyt.cpp inc/odczyt.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o out/obj/odczyt.o src/odczyt.cpp

out/obj/okno.o: src/okno.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o out/obj/okno.o src/okno.cpp

out/obj/oknogry.o: src/oknogry.cpp inc/oknogry.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o out/obj/oknogry.o src/oknogry.cpp

out/obj/statisticWidget.o: src/statisticWidget.cpp inc/statisticWidget.hpp \
		inc/mainWidget.hpp \
		inc/gameWindow.hpp \
		inc/dialogs.hpp \
		out/uic/ui_disDialog.h \
		out/uic/ui_conDialog.h \
		out/uic/ui_gameWindow.h \
		inc/gameWidget.hpp \
		out/uic/ui_gameWidget.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o out/obj/statisticWidget.o src/statisticWidget.cpp

out/obj/test.o: src/test.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o out/obj/test.o src/test.cpp

out/obj/widgetgry.o: src/widgetgry.cpp inc/widgetgry.hpp \
		inc/odczyt.hpp \
		out/uic/ui_gameWidget.h \
		out/uic/ui_gameWindow.h \
		out/uic/ui_disDialog.h \
		out/uic/ui_conDialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o out/obj/widgetgry.o src/widgetgry.cpp

out/obj/qrc_zasoby.o: out/rcc/qrc_zasoby.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o out/obj/qrc_zasoby.o out/rcc/qrc_zasoby.cpp

out/obj/moc_dialogs.o: out/moc/moc_dialogs.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o out/obj/moc_dialogs.o out/moc/moc_dialogs.cpp

out/obj/moc_gameWidget.o: out/moc/moc_gameWidget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o out/obj/moc_gameWidget.o out/moc/moc_gameWidget.cpp

out/obj/moc_gameWindow.o: out/moc/moc_gameWindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o out/obj/moc_gameWindow.o out/moc/moc_gameWindow.cpp

out/obj/moc_mainWidget.o: out/moc/moc_mainWidget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o out/obj/moc_mainWidget.o out/moc/moc_mainWidget.cpp

out/obj/moc_statisticWidget.o: out/moc/moc_statisticWidget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o out/obj/moc_statisticWidget.o out/moc/moc_statisticWidget.cpp

####### Install

install:  FORCE

uninstall:  FORCE

FORCE:

